//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>About </summary>
	[PublishedModel("aboutPage")]
	public partial class AboutPage : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "aboutPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<AboutPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public AboutPage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// About - Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutBackgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops AboutBackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "aboutBackgroundImage");

		///<summary>
		/// About - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutHeadline")]
		public virtual string AboutHeadline => this.Value<string>(_publishedValueFallback, "aboutHeadline");

		///<summary>
		/// About - Link 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutLink1")]
		public virtual string AboutLink1 => this.Value<string>(_publishedValueFallback, "aboutLink1");

		///<summary>
		/// About - Link 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutLink2")]
		public virtual string AboutLink2 => this.Value<string>(_publishedValueFallback, "aboutLink2");

		///<summary>
		/// About - Link Text 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutLinkText1")]
		public virtual string AboutLinkText1 => this.Value<string>(_publishedValueFallback, "aboutLinkText1");

		///<summary>
		/// About - Link Text 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("aboutLinkText2")]
		public virtual string AboutLinkText2 => this.Value<string>(_publishedValueFallback, "aboutLinkText2");

		///<summary>
		/// Ceo - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoHeadline")]
		public virtual string CeoHeadline => this.Value<string>(_publishedValueFallback, "ceoHeadline");

		///<summary>
		/// Ceo - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CeoImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ceoImage");

		///<summary>
		/// Ceo - Quote
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoQuote")]
		public virtual string CeoQuote => this.Value<string>(_publishedValueFallback, "ceoQuote");

		///<summary>
		/// Ceo - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString CeoText => this.Value<global::Umbraco.Cms.Core.Strings.IHtmlEncodedString>(_publishedValueFallback, "ceoText");

		///<summary>
		/// Our Experts - Expert 1 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsExpert1Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertsExpert1Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertsExpert1Image");

		///<summary>
		/// Our Experts - Expert 1 - Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsExpert1Name")]
		public virtual string OurExpertsExpert1Name => this.Value<string>(_publishedValueFallback, "ourExpertsExpert1Name");

		///<summary>
		/// Our Experts - Expert 1 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsExpert1Text")]
		public virtual string OurExpertsExpert1Text => this.Value<string>(_publishedValueFallback, "ourExpertsExpert1Text");

		///<summary>
		/// Our Experts - Expert 2 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsExpert2Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertsExpert2Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertsExpert2Image");

		///<summary>
		/// Our Experts - Expert 2 - Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsExpert2Name")]
		public virtual string OurExpertsExpert2Name => this.Value<string>(_publishedValueFallback, "ourExpertsExpert2Name");

		///<summary>
		/// Our Experts - Expert 2 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsExpert2Text")]
		public virtual string OurExpertsExpert2Text => this.Value<string>(_publishedValueFallback, "ourExpertsExpert2Text");

		///<summary>
		/// Our Experts - Expert 3 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsExpert3Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertsExpert3Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertsExpert3Image");

		///<summary>
		/// Our Experts - Expert 3 - Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsExpert3Name")]
		public virtual string OurExpertsExpert3Name => this.Value<string>(_publishedValueFallback, "ourExpertsExpert3Name");

		///<summary>
		/// Our Experts - Expert 3 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsExpert3Text")]
		public virtual string OurExpertsExpert3Text => this.Value<string>(_publishedValueFallback, "ourExpertsExpert3Text");

		///<summary>
		/// Our Experts - Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsHeading")]
		public virtual string OurExpertsHeading => this.Value<string>(_publishedValueFallback, "ourExpertsHeading");

		///<summary>
		/// Our Experts - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsHeadline")]
		public virtual string OurExpertsHeadline => this.Value<string>(_publishedValueFallback, "ourExpertsHeadline");

		///<summary>
		/// Our Experts - More Expert 1 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert1Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertsMoreExpert1Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertsMoreExpert1Image");

		///<summary>
		/// Our Experts - More Expert 1 - Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert1Name")]
		public virtual string OurExpertsMoreExpert1Name => this.Value<string>(_publishedValueFallback, "ourExpertsMoreExpert1Name");

		///<summary>
		/// Our Experts - More Expert 1 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert1Text")]
		public virtual string OurExpertsMoreExpert1Text => this.Value<string>(_publishedValueFallback, "ourExpertsMoreExpert1Text");

		///<summary>
		/// Our Experts - More Expert 2 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert2Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertsMoreExpert2Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertsMoreExpert2Image");

		///<summary>
		/// Our Experts - More Expert 2 - Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert2Name")]
		public virtual string OurExpertsMoreExpert2Name => this.Value<string>(_publishedValueFallback, "ourExpertsMoreExpert2Name");

		///<summary>
		/// Our Experts - More Expert 2 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert2Text")]
		public virtual string OurExpertsMoreExpert2Text => this.Value<string>(_publishedValueFallback, "ourExpertsMoreExpert2Text");

		///<summary>
		/// Our Experts - More Expert 3 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert3Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertsMoreExpert3Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertsMoreExpert3Image");

		///<summary>
		/// Our Experts - More Expert 3 - Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert3Name")]
		public virtual string OurExpertsMoreExpert3Name => this.Value<string>(_publishedValueFallback, "ourExpertsMoreExpert3Name");

		///<summary>
		/// Our Experts - More Expert 3 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert3Text")]
		public virtual string OurExpertsMoreExpert3Text => this.Value<string>(_publishedValueFallback, "ourExpertsMoreExpert3Text");

		///<summary>
		/// Our Experts - More Expert 4 - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert4Image")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OurExpertsMoreExpert4Image => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ourExpertsMoreExpert4Image");

		///<summary>
		/// Our Experts - More Expert 4 - Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert4Name")]
		public virtual string OurExpertsMoreExpert4Name => this.Value<string>(_publishedValueFallback, "ourExpertsMoreExpert4Name");

		///<summary>
		/// Our Experts - More Expert 4 - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertsMoreExpert4Text")]
		public virtual string OurExpertsMoreExpert4Text => this.Value<string>(_publishedValueFallback, "ourExpertsMoreExpert4Text");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// reviews - Bank
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsBank")]
		public virtual string ReviewsBank => this.Value<string>(_publishedValueFallback, "reviewsBank");

		///<summary>
		/// reviews - Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsHeading")]
		public virtual string ReviewsHeading => this.Value<string>(_publishedValueFallback, "reviewsHeading");

		///<summary>
		/// reviews - Headline
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsHeadline")]
		public virtual string ReviewsHeadline => this.Value<string>(_publishedValueFallback, "reviewsHeadline");

		///<summary>
		/// reviews - Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ReviewsImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "reviewsImage");

		///<summary>
		/// reviews - Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsName")]
		public virtual string ReviewsName => this.Value<string>(_publishedValueFallback, "reviewsName");

		///<summary>
		/// reviews - Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviewsText")]
		public virtual string ReviewsText => this.Value<string>(_publishedValueFallback, "reviewsText");
	}
}
